### ISSUE TITLE
Project is stripped after X Values

### ISSUE THREAD

**Issue by markusspitzli** [guilhemmarchand/TA-jira-service-desk-simple-addon#3] opened 2020-04-24 09:12 UTC
We have a lot of Projects on our Jira Instance. So many that It doesn't show all Projects when creating an alert.

It would be great if all Projects are shown. maybe with a parameter like max_list_projects in the configuration file.

**Comment by guilhemmarchand** [comment] 2020-04-24 11:45
Acknowledged.

Does the list of project gets truncated at the command level, or within the dropdown selection @markusspitzli ?

Running the Get projects report or custom command direclty.

Thanks

**Comment by markusspitzli** [comment] 2020-04-24 13:13
The list is truncated at the dropdown section. 

Running the Get Project report delivers the complete list.

**Comment by guilhemmarchand** [comment] 2020-04-24 22:34
This is a bit strange @markusspitzli 

I actually tested by simulating the listing of the projects via a CSV file from the dropdown (instead of the call to the jirafill command), and could get up 1500 entries listed in the dropdown:

![image](https://user-images.githubusercontent.com/7503059/80261901-b7295b00-8683-11ea-96bb-045e27c10b2e.png)

since you confirmed that the Get project report provides the complete list of projects in your JIRA instances this seems a bit suspicious.

One alternative I am thinking of could be to provide a similar option to the dynamic priorities which would override the project definition if it has been set.
This effectively would allow defining the project event if it is not listed, and additionally provide dynamic options to define the project as part of the search logic via tokens.

Let me know your thinking

**Comment by markusspitzli** [comment] 2020-04-27 07:49
@guilhemmarchand I prefere defining the project even if it is not listed.

**Comment by guilhemmarchand** [comment] 2020-04-27 08:41
@markusspitzli 

Yes the best by far would be to understand / fix that truncation, I could't reproduce it on my end.
How many projects are there in your instance ?

Safety double check, does:

```
| jirafill opt=1 | stats count by key, key_projects | dedup key_projects | sort key_projects | fields key, key_projects
| stats c
```

Provides the exact number of unique projects ?

**Comment by guilhemmarchand** [comment] 2020-06-15 21:13
Hi @markusspitzli 

Is is still an issue or shall we close this one ?

Thank you

Guilhem

**Comment by guilhemmarchand** [comment] 2020-06-19 12:56
Closed for inactivity.

**Closed by guilhemmarchand** 2020-06-19 12:56 UTC
